"""initial schema

Revision ID: 2e1b104cf8bc
Revises:
Create Date: 2025-07-30 23:10:22.333625

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2e1b104cf8bc"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "anomalies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("threat_level", sa.Integer(), nullable=False),
        sa.Column("is_resolved", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_anomalies_category"), "anomalies", ["category"], unique=False
    )
    op.create_table(
        "agent_reports",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("anomaly_id", sa.String(length=36), nullable=False),
        sa.Column("agent_name", sa.String(), nullable=False),
        sa.Column("report_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["anomaly_id"],
            ["anomalies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "anomaly_attributes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("anomaly_id", sa.String(length=36), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["anomaly_id"],
            ["anomalies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("anomaly_attributes")
    op.drop_table("agent_reports")
    op.drop_index(op.f("ix_anomalies_category"), table_name="anomalies")
    op.drop_table("anomalies")
    # ### end Alembic commands ###
